Pages/Chores/ChoreCreate.cshtml.cs
using ChoreMgr.Data;
using ChoreMgr.Models;
using ChoreMgr.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ChoreMgr.Pages.Chores
{
    public class ChoreCreateModel : BasePageModel
    {
        private readonly ChoreJsonDb _service;

        public ChoreCreateModel(ChoreJsonDb choreService)
        {
            _service = choreService;
        }

        public IActionResult OnGet()
        {
            DanLogger.LogView(HttpContext);
            if (!IsAuthed())
                return RedirectToPage("/Shared/Unauthorized");

            return Page();
        }

        [BindProperty]
        public Job Job { get; set; }

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            DanLogger.LogChange(HttpContext, Job);
            if (!IsAuthed())
                return RedirectToPage("/Shared/Unauthorized");
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _service.CreateJob(Job, UserName);
        
            return RedirectToPage("./ChoreIndex");
        }
    }
}

Pages/Chores/ChoreEdit.cshtml.cs
using ChoreMgr.Data;
using ChoreMgr.Models;
using ChoreMgr.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ChoreMgr.Pages.Chores
{
    public class ChoreEditModel : BasePageModel
    {
        private readonly ChoreJsonDb _service;

        public ChoreEditModel(ChoreJsonDb choreService)
        {
            _service = choreService;
        }

        [BindProperty]
        public JobModel JobModel { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            DanLogger.LogView(HttpContext);
            if (!IsAuthed())
                return RedirectToPage("/Shared/Unauthorized");

            if (id == null)
                return NotFound();

            var jobModel = _service.GetJobModel(id, includeLogs: true);
            if (jobModel == null)
                return NotFound();
            JobModel = jobModel;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            DanLogger.LogChange(HttpContext, JobModel);
            if (!IsAuthed())
                return RedirectToPage("/Shared/Unauthorized");

            if (!ModelState.IsValid)
            {
                return Page();
            }
            _service.UpdateJob(JobModel, UserName);
            return RedirectToPage("./ChoreIndex");
        }
        public IActionResult OnGetDelete(string id)
        {
            DanLogger.LogChange(HttpContext);
            if (!IsAuthed())
                return RedirectToPage("/Shared/Unauthorized");

            _service.RemoveJob(id, UserName);
            return RedirectToPage("./ChoreIndex");
        }
    }
}

Pages/Chores/ChoreIndex.cshtml.cs
using ChoreMgr.Data;
using ChoreMgr.Models;
using ChoreMgr.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace ChoreMgr.Pages.Chores
{
    // TODO Include user model
    // TODO Add size to jobs
    // TODONE allow to run in IIS not at root

    public class ChoreIndexModel : BasePageModel
    {
        private readonly ChoreJsonDb _service;

        public ChoreIndexModel(ChoreJsonDb choreService)
        {
            _service = choreService;
        }

        public string ContextName
        {
            get
            {
                return _service.ToString();
            }
        }
        public bool IsDebug
        {
            get
            {
                return System.Diagnostics.Debugger.IsAttached;
            }
        }
        public IList<JobModel> JobList { get; set; }

        [BindProperty]
        // a list of categories to exclude, each category is one character, or a limit of new tasks to avoid being overwhelmed
        public string ExcludeList { get; set; }

        public string Summary
        {
            get
            {
                var today = DateTime.Today;
                var yesterday = today.AddDays(-1);
                var recentJobLogs = _service.GetJobLogs().Where(j => j.DoneDate >= yesterday);
                var todayCount = recentJobLogs.Where(j => j.DoneDate >= today).DistinctBy(j => j.JobName).Count();
                var yesterdayCount = recentJobLogs.Where(j => j.DoneDate >= yesterday && j.DoneDate < today).DistinctBy(j => j.JobName).Count();
                return $"Done Today: {todayCount} " +
                        $"Yesterday: {yesterdayCount}";
            }
        }
        public string Pending
        {
            get
            {
                var today = DateTime.Today;
                return $"Due today: {JobList.Count(j => j.NextDo?.Date == today)} " +
                        $"Past due: {JobList.Count(j => j.NextDo?.Date < today)}";
            }
        }
        public IActionResult OnGetAsync(string? forWhom)
        {
            DanLogger.LogView(HttpContext, ContextName);
            if (!IsAuthed())
                return RedirectToPage("/Shared/Unauthorized");

            ExcludeList = GetFromSession("ExcludeList", "");
            if (int.TryParse(ExcludeList, out int enough))
            {
                var jobs = _service.GetJobModels();
                var list = jobs.Where(j => j.Status == "❕" || j.Status == "✅").ToList();
                var notDone = jobs.Where(j => j.Status == "❌").ToList();
                list.AddRange(GetSome(notDone, enough));
                JobList = list.OrderBy(j => j.NextDo).ToList();
            }
            else
            {
                var excludeList = ExcludeList.ToCharArray();
                JobList = _service.GetJobModels().Where(j => !j.IsExcluded(excludeList)).OrderBy(j => j.NextDo).ToList();
            }
            return Page();
        }
        Random _rnd = new Random();
        private IEnumerable<JobModel> GetSome(List<JobModel> jobs, int n)
        {
            var rv = new List<JobModel>();
            while (rv.Count() < n)
            {
                var job = jobs[_rnd.Next(jobs.Count)];
                if (!rv.Contains(job))
                    rv.Add(job);
            }
            return rv;
        }

        public IActionResult OnPostAsync(object o)
        {
            DanLogger.LogView(HttpContext, "Change filter to-" + ExcludeList);
            SetToSession("ExcludeList", ExcludeList);

            return RedirectToPage("./ChoreIndex");
        }
        public IActionResult OnPostQuickCreateAsync(object o)
        {
            if (string.IsNullOrWhiteSpace(ExcludeList))
                return RedirectToPage("./ChoreCreate");

            DanLogger.LogChange(HttpContext, ExcludeList);
            if (!IsAuthed())
                return RedirectToPage("/Shared/Unauthorized");
            var newJob = new Job() { Name = ExcludeList };
            _service.CreateJob(newJob, UserName);

            return RedirectToPage("./ChoreIndex");
        }

        public IActionResult OnGetProdSync()
        {
            DanLogger.LogChange(HttpContext);
            if (!IsAuthed())
                return RedirectToPage("/Shared/Unauthorized");
            _service.ProdSync();

            return RedirectToPage("./ChoreIndex");
        }
        public IActionResult OnGetBackup()
        {
            DanLogger.LogChange(HttpContext);
            if (!IsAuthed())
                return RedirectToPage("/Shared/Unauthorized");
            _service.Backup();
            return RedirectToPage("./ChoreIndex");
        }
        public IActionResult OnGetToday(string id)
        {
            return UpdateChore(id, DateTime.Today);
        }
        public IActionResult OnGetYesterday(string id)
        {
            return UpdateChore(id, DateTime.Today.AddDays(-1));
        }
        IActionResult UpdateChore(string id, DateTime date)
        {
            DanLogger.LogChange(HttpContext, date);
            if (!IsAuthed())
                return RedirectToPage("/Shared/Unauthorized");
            var jobModel = _service.GetJobModel(id);
            if (jobModel == null)
                return Page();

            jobModel.LastDone = date;
            _service.UpdateJob(jobModel, UserName);

            return RedirectToPage("./ChoreIndex");
        }
    }
}

Pages/Chores/Create.cshtml.cs
using ChoreMgr.Data;
using ChoreMgr.Models;
using ChoreMgr.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ChoreMgr.Pages.Chores
{
    public class CreateModel : BasePageModel
    {
        private readonly ChoreJsonDb _service;

        public CreateModel(ChoreJsonDb choreService)
        {
            _service = choreService;
        }

        public IActionResult OnGet()
        {
            DanLogger.LogView(HttpContext);
            return Page();
        }

        [BindProperty]
        public Job Job { get; set; }

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            DanLogger.LogChange(HttpContext, Job);
            if (!IsAuthed())
                return RedirectToPage("/Shared/Unauthorized");
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _service.CreateJob(Job, UserName);
        
            return RedirectToPage("./Index");
        }
    }
}

Pages/Chores/Edit.cshtml.cs
using ChoreMgr.Data;
using ChoreMgr.Models;
using ChoreMgr.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ChoreMgr.Pages.Chores
{
    public class EditModel : BasePageModel
    {
        private readonly ChoreJsonDb _service;

        public EditModel(ChoreJsonDb choreService)
        {
            _service = choreService;
        }

        [BindProperty]
        public JobModel JobModel { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            DanLogger.LogView(HttpContext);
            if (!IsAuthed())
                return RedirectToPage("/Shared/Unauthorized");

            if (id == null)
                return NotFound();

            var jobModel = _service.GetJobModel(id, includeLogs: true);
            if (jobModel == null)
                return NotFound();
            JobModel = jobModel;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            DanLogger.LogChange(HttpContext, JobModel);

            if (!ModelState.IsValid)
            {
                return Page();
            }
            _service.UpdateJob(JobModel, UserName);
            return RedirectToPage("./ChoreIndex");
        }
        public IActionResult OnGetDelete(string id)
        {
            DanLogger.LogChange(HttpContext);
            _service.RemoveJob(id, UserName);
            return RedirectToPage("./ChoreIndex");
        }
    }
}

Pages/Chores/Index.cshtml.cs
using ChoreMgr.Data;
using ChoreMgr.Models;
using ChoreMgr.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace ChoreMgr.Pages.Chores
{
    // TODO Include user model
    // TODO Add size to jobs
    // TODONE allow to run in IIS not at root

    public class IndexModel : BasePageModel
    {
        private readonly ChoreJsonDb _service;

        public IndexModel(ChoreJsonDb choreService)
        {
            _service = choreService;
        }

        public string ContextName
        {
            get
            {
                return _service.ToString();
            }
        }
        public bool IsDebug
        {
            get
            {
                return System.Diagnostics.Debugger.IsAttached;
            }
        }
        public IList<JobModel> JobList { get; set; }

        [BindProperty] 
        public string ExcludeList { get; set; }

        public string Summary
        {
            get
            {
                var today = DateTime.Today;
                var yesterday = today.AddDays(-1);
                var recentJobLogs = _service.GetJobLogs().Where(j => j.DoneDate >= yesterday);
                var todayCount = recentJobLogs.Where(j => j.DoneDate >= today).DistinctBy(j => j.JobName).Count();
                var yesterdayCount = recentJobLogs.Where(j => j.DoneDate >= yesterday && j.DoneDate < today).DistinctBy(j => j.JobName).Count();
                return $"Done Today: {todayCount} " +
                        $"Yesterday: {yesterdayCount}";
            }
        }
        public string Pending
        {
            get
            {
                var today = DateTime.Today;
                return $"Due today: {JobList.Count(j => j.NextDo?.Date == today)} " +
                        $"Past due: {JobList.Count(j => j.NextDo?.Date < today)}";
            }
        }
        string GetFromSession(string key, string def)
        {
            if (!HttpContext.Session.Keys.Contains(key))
                return def;

            var rv = HttpContext.Session.GetString(key);
            if (string.IsNullOrEmpty(rv))
                return def;
            return rv;
        }
        void SetToSession(string key, string? val)
        {
            if (string.IsNullOrWhiteSpace(val))
                HttpContext.Session.Remove(key);
            else
                HttpContext.Session.SetString(key, val);
        }
        public void OnGetAsync(string? forWhom)
        {
            DanLogger.LogView(HttpContext, ContextName);
            ExcludeList = GetFromSession("ExcludeList", "");
            var excludeList = ExcludeList.ToCharArray();
            JobList = _service.GetJobModels().Where(j => !j.IsExcluded(excludeList)).OrderBy(j => j.NextDo).ToList();
        }
        public IActionResult OnPostAsync(object o)
        {
            DanLogger.LogView(HttpContext, "Change filter to-" + ExcludeList);
            SetToSession("ExcludeList", ExcludeList);

            return RedirectToPage("./Index");
        }

        public IActionResult OnGetProdSync()
        {
            DanLogger.LogChange(HttpContext);
            if (!IsAuthed())
                return RedirectToPage("/Shared/Unauthorized");
            _service.ProdSync();

            return RedirectToPage("./Index");
        }
        public IActionResult OnGetBackup()
        {
            DanLogger.LogChange(HttpContext);
            if (!IsAuthed())
                return RedirectToPage("/Shared/Unauthorized");
            _service.Backup();
            return RedirectToPage("./Index");
        }
        public IActionResult OnGetToday(string id)
        {
            return UpdateChore(id, DateTime.Today);
        }
        public IActionResult OnGetYesterday(string id)
        {
            return UpdateChore(id, DateTime.Today.AddDays(-1));
        }
        IActionResult UpdateChore(string id, DateTime date)
        {
            DanLogger.LogChange(HttpContext, date);
            if (!IsAuthed())
                return RedirectToPage("/Shared/Unauthorized");
            var jobModel = _service.GetJobModel(id);
            if (jobModel == null)
                return Page();

            jobModel.LastDone = date;
            _service.UpdateJob(jobModel, UserName);

            return RedirectToPage("./Index");
        }
    }
}

Pages/Chores/Journal.cshtml.cs
using ChoreMgr.Data;
using ChoreMgr.Models;
using ChoreMgr.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ChoreMgr.Pages.Chores
{
    public class JournalModel : BasePageModel
    {
        private readonly ChoreJsonDb _service;

        public JournalModel(ChoreJsonDb choreService)
        {
            _service = choreService;
        }

        public IList<JobLog> JobLogList{ get;set; }
        public List<Daily> DailyList { get; private set; }

        public void OnGetAsync()
        {
            DanLogger.LogView(HttpContext);
            JobLogList = _service.GetJobLogs().OrderByDescending(j => j.Updated).ToList();
            var dailyList = new List<Daily>();
            var byDay = JobLogList.GroupBy(j => j.DoneDate);
            foreach (var day in byDay)
            {
                if (day.Key == null)
                    continue;
                dailyList.Add(new Daily(day.Key.Value, day.DistinctBy(d => d.JobName).Count()));
            }
            DailyList = dailyList.OrderByDescending(d => d.DoneDate).ToList();
        }
        public void OnGetByDay(DateTime? date)
        {
            DanLogger.LogView(HttpContext);
            JobLogList = _service.GetJobLogs().Where(j => j.DoneDate == date).OrderBy(j => j.JobName).ToList();
        }
    }
}

Pages/Chores/ChoreEdit.cshtml
@page
@model ChoreMgr.Pages.Chores.ChoreEditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Job ID:@Model.JobModel.Id</h4>
<hr />
<script type="text/javascript">
    function setIntervalDays(days) {
        if (!isNaN(days))
            document.getElementById("JobModel_IntervalDays").value = days;
    }
</script>
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="JobModel.Id" />
            <div class="form-group">
                <label asp-for="JobModel.Name" class="control-label"></label>
                <input asp-for="JobModel.Name" class="form-control" />
                <span asp-validation-for="JobModel.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="JobModel.Category" class="control-label"></label>
                <input asp-for="JobModel.Category" class="form-control" />
            </div>
            <div class="form-group">
                <label class="control-label">Interval (days)</label>
                <input asp-for="JobModel.IntervalDays" class="form-control" />
                <span asp-validation-for="JobModel.IntervalDays" class="text-danger"></span>
            </div>
            <a href="javascript:setIntervalDays(1);">Daily</a>
            <a href="javascript:setIntervalDays(7);">Weekly</a>
            <a href="javascript:setIntervalDays(14);">Fortnightly</a>
            <a href="javascript:setIntervalDays(30);">Monthly</a>
            <a href="javascript:setIntervalDays(90);">Quarterly</a>
            <a href="javascript:setIntervalDays(365);">Yearly</a>
            <div class="form-group">
                <label class="control-label">Last Done</label>
                <input asp-for="JobModel.LastDone" class="form-control" />
                <span asp-validation-for="JobModel.LastDone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./ChoreIndex">Back to List</a>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.JobModel.Logs[0].Updated)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JobModel.Logs[0].DoneDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JobModel.Logs[0].Note)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.JobModel.Logs) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Updated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DoneDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Note)
            </td>
        </tr>
        }
    </tbody>
</table>

<div>
    <a asp-page-handler="Delete" asp-route-id="@Model.JobModel.Id">Delete</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Chores/ChoreIndex.cshtml
@page
@model ChoreMgr.Pages.Chores.ChoreIndexModel

@{
    ViewData["Title"] = "Chores";
}
<script>
    console.log("onload called"); // Do not send to your backend! Use an ID token instead.
    document.cookie = "yo=yoyo";
</script>
<h1>Chores </h1>
<div style="float: left">
    <a asp-page="./Journal">Summary: @Model.Summary</a> <br />
    Pending: @Model.Pending <br />
    <a asp-page="ChoreCreate">Create New</a>
</div>

<div style="float: right">
    @if (Model.IsDebug)
    {
        <a asp-page-handler="ProdSync">Prod Sync</a>  <br />
    }
    <a asp-page-handler="Backup">Backup</a>  <br />
    <form method="post">
            <input asp-for="ExcludeList" class="form-control" />
            <span asp-validation-for="ExcludeList" class="text-danger"></span>
            <input type="submit" value="Update" class="btn btn-primary" />
            <input type="submit" value="Quick Create" class="btn btn-primary"  asp-page-handler="QuickCreate" />
    </form>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.JobList[0].Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JobList[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JobList[0].Category)
            </th>
            <th style="text-align:center;">
                @Html.DisplayNameFor(model => model.JobList[0].IntervalDays)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JobList[0].LastDone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JobList[0].NextDo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.JobList) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td style=@item.WebStyle>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td style="text-align:center;">
                @Html.DisplayFor(modelItem => item.Category)
            </td>
            <td style="text-align:center;">
                @Html.DisplayFor(modelItem => item.IntervalDays)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastDone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NextDo)
            </td>
            <td>
                <a asp-page-handler="Today" asp-route-id="@item.Id">Today</a>
                <a asp-page-handler="Yesterday" asp-route-id="@item.Id">Yest</a>
                <a asp-page="./ChoreEdit" asp-route-id="@item.Id">Edit</a>
            </td>
        </tr>
}
    </tbody>
</table>
@Model.ContextName
    

Pages/Chores/Edit.cshtml
@page
@model ChoreMgr.Pages.Chores.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Job ID:@Model.JobModel.Id</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="JobModel.Id" />
            <div class="form-group">
                <label asp-for="JobModel.Name" class="control-label"></label>
                <input asp-for="JobModel.Name" class="form-control" />
                <span asp-validation-for="JobModel.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="JobModel.Category" class="control-label"></label>
                <input asp-for="JobModel.Category" class="form-control" />
            </div>
            <div class="form-group">
                <label class="control-label">Interval (days)</label>
                <input asp-for="JobModel.IntervalDays" class="form-control" />
                <span asp-validation-for="JobModel.IntervalDays" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Last Done</label>
                <input asp-for="JobModel.LastDone" class="form-control" />
                <span asp-validation-for="JobModel.LastDone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./ChoreIndex">Back to List</a>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.JobModel.Logs[0].Updated)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JobModel.Logs[0].DoneDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JobModel.Logs[0].Note)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.JobModel.Logs) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Updated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DoneDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Note)
            </td>
        </tr>
        }
    </tbody>
</table>

<div>
    <a asp-page-handler="Delete" asp-route-id="@Model.JobModel.Id">Delete</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Chores/Index.cshtml
@page
@model ChoreMgr.Pages.Chores.IndexModel

@{
    ViewData["Title"] = "Chores";
}
<script>
    console.log("onload called"); // Do not send to your backend! Use an ID token instead.
    document.cookie = "yo=yoyo";
</script>
<h1>Chores </h1>
    <div style="float: left">
        <a asp-page="./Journal">Summary: @Model.Summary</a> <br />
        Pending: @Model.Pending <br />
        <a asp-page="Create">Create New</a>
    </div>

    <div style="float: right">
        @if (Model.IsDebug)
        {
            <a asp-page-handler="ProdSync">Prod Sync</a>  <br />
        }
        <a asp-page-handler="Backup">Backup</a>  <br />
        <form method="post">
                <input asp-for="ExcludeList" class="form-control" />
                <span asp-validation-for="ExcludeList" class="text-danger"></span>
                <input type="submit" value="Update" class="btn btn-primary" />
        </form>
    </div>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.JobList[0].Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JobList[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JobList[0].Category)
            </th>
            <th style="text-align:center;">
                @Html.DisplayNameFor(model => model.JobList[0].IntervalDays)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JobList[0].LastDone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JobList[0].NextDo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.JobList) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td style=@item.WebStyle>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td style="text-align:center;">
                @Html.DisplayFor(modelItem => item.Category)
            </td>
            <td style="text-align:center;">
                @Html.DisplayFor(modelItem => item.IntervalDays)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastDone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NextDo)
            </td>
            <td>
                <a asp-page-handler="Today" asp-route-id="@item.Id">Today</a>
                <a asp-page-handler="Yesterday" asp-route-id="@item.Id">Yest</a>
                <a asp-page="./Edit" asp-route-id="@item.Id">Edit</a>
            </td>
        </tr>
}
    </tbody>
</table>
@Model.ContextName
    