Pages/Transactions/TransactionCreate.cshtml.cs
using ChoreMgr.Data;
using ChoreMgr.Models;
using ChoreMgr.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ChoreMgr.Pages.Chores
{
    public class TransactionCreateModel : BasePageModel
    {
        private readonly ChoreJsonDb _service;

        public TransactionCreateModel(ChoreJsonDb choreService)
        {
            _service = choreService;
        }

        public IActionResult OnGet()
        {
            DanLogger.LogView(HttpContext);
            if (!IsAuthed())
                return RedirectToPage("/Shared/Unauthorized");

            Transaction = new Transaction();
            return Page();
        }

        [BindProperty]
        public Transaction Transaction { get; set; }

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            DanLogger.LogChange(HttpContext, Transaction);
            if (!IsAuthed())
                return RedirectToPage("/Shared/Unauthorized");
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _service.CreateTransaction(Transaction, UserName);
        
            return RedirectToPage("./TransactionIndex");
        }
    }
}

Pages/Transactions/TransactionEdit.cshtml.cs
using ChoreMgr.Data;
using ChoreMgr.Models;
using ChoreMgr.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ChoreMgr.Pages.Chores
{
    public class TransactionEditModel : BasePageModel
    {
        private readonly ChoreJsonDb _service;

        public TransactionEditModel(ChoreJsonDb choreService)
        {
            _service = choreService;
        }

        [BindProperty]
        public Transaction Transaction { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            DanLogger.LogView(HttpContext);
            if (!IsAuthed())
                return RedirectToPage("/Shared/Unauthorized");

            if (id == null)
                return NotFound();

            var transaction = _service.GetTransaction(id);
            if (transaction == null)
                return NotFound();
            Transaction = transaction;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            DanLogger.LogChange(HttpContext, Transaction);
            if (!IsAuthed())
                return RedirectToPage("/Shared/Unauthorized");

            if (!ModelState.IsValid)
            {
                return Page();
            }
            _service.UpdateTransaction(Transaction, UserName);
            return RedirectToPage("./TransactionIndex");
        }
        public IActionResult OnGetDelete(string id)
        {
            DanLogger.LogChange(HttpContext);
            if (!IsAuthed())
                return RedirectToPage("/Shared/Unauthorized");
            _service.RemoveTransaction(id, UserName);
            return RedirectToPage("./TransactionIndex");
        }
    }
}

Pages/Transactions/TransactionIndex.cshtml.cs
using ChoreMgr.Data;
using ChoreMgr.Models;
using ChoreMgr.Utils;
using Microsoft.AspNetCore.Mvc;

namespace ChoreMgr.Pages.Transactions
{
    // TODO Include user model
    // TODO Add size to jobs
    // TODONE allow to run in IIS not at root

    public class TransactionIndexModel : BasePageModel
    {
        private readonly ChoreJsonDb _service;

        public TransactionIndexModel(ChoreJsonDb choreService)
        {
            _service = choreService;
        }

        public string ContextName
        {
            get
            {
                return _service.ToString();
            }
        }
        public bool IsDebug
        {
            get
            {
                return System.Diagnostics.Debugger.IsAttached;
            }
        }
        public string Total
        {
            get
            {
                var total = TransactionList.Sum(s => s.Amount);
                return total.ToString("C0") + $"({TransactionList.Count()})";
            }
        }
        public TransactionModel[] TransactionList { get; set; }

        [BindProperty] 
        public string ExcludeList { get; set; }

        public IActionResult OnGetAsync(string? forWhom)
        {
            DanLogger.LogView(HttpContext, ContextName);
            if (!IsAuthed())
                return RedirectToPage("/Shared/Unauthorized");
            TransactionList = _service.GetTransactionModels().OrderByDescending(t => t.Timestamp).ToArray();
            return Page();
        }
        public IActionResult OnGetDup(string id)
        {
            DanLogger.LogChange(HttpContext);
            if (!IsAuthed())
                return RedirectToPage("/Shared/Unauthorized");
            var transaction = _service.GetTransaction(id);
            if (transaction == null)
                return NotFound();
            var createdTransaction = _service.CreateTransaction(Transaction.Duplicate(transaction), UserName);

            if (createdTransaction?.Id == null)
                return NotFound();
            //http://localhost:5165/Transactions/TransactionEdit?id=645bce6a-0d1b-427e-8142-f1f98dbdaea8
            var routeValues = new Dictionary<string, object>();
            routeValues["id"] = createdTransaction.Id;
            return RedirectToPage("./TransactionEdit", routeValues);
        }
        public IActionResult OnGetProdSync()
        {
            DanLogger.LogChange(HttpContext);
            if (!IsAuthed())
                return RedirectToPage("/Shared/Unauthorized");
            _service.ProdSync();

            return RedirectToPage("./TransactionIndex");
        }
        public IActionResult OnGetBackup()
        {
            DanLogger.LogChange(HttpContext);
            if (!IsAuthed())
                return RedirectToPage("/Shared/Unauthorized");
            _service.Backup();
            return RedirectToPage("./TransactionIndex");
        }
        public IActionResult OnGetDedup()
        {
            DanLogger.LogChange(HttpContext);
            if (!IsAuthed())
                return RedirectToPage("/Shared/Unauthorized");
            _service.DedupTransactions();
            return RedirectToPage("./TransactionIndex");
        }

        // TODONE handle repeat/duplicate
    }
}

Pages/Transactions/TransactionCreate.cshtml
@page
@model ChoreMgr.Pages.Chores.TransactionCreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Transaction</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Transaction.Name" class="control-label"></label>
                <input asp-for="Transaction.Name" class="form-control" />
                <span asp-validation-for="Transaction.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Transaction.Amount" class="control-label"></label>
                <input asp-for="Transaction.Amount" class="form-control" asp-format="{0:N0}"/>
                <span asp-validation-for="Transaction.Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Transaction.Category" class="control-label"></label>
                <input asp-for="Transaction.Category" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Transaction.Notes" class="control-label"></label>
                <input asp-for="Transaction.Notes" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Transaction.Timestamp" class="control-label"></label>
                <input asp-for="Transaction.Timestamp" class="form-control" asp-format="{0:yyyy-MM-ddTHH:mm}"/>
                <span asp-validation-for="Transaction.Timestamp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="TransactionIndex">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Transactions/TransactionEdit.cshtml
@page
@model ChoreMgr.Pages.Chores.TransactionEditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Job ID:@Model.Transaction.Id</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Transaction.Id" />
            <div class="form-group">
                <label asp-for="Transaction.Name" class="control-label"></label>
                <input asp-for="Transaction.Name" class="form-control" />
                <span asp-validation-for="Transaction.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Transaction.Amount" class="control-label" asp-format="{0:N0}"></label>
                <input asp-for="Transaction.Amount" class="form-control" />
                <span asp-validation-for="Transaction.Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Transaction.Timestamp" class="control-label"></label>
                <input asp-for="Transaction.Timestamp" class="form-control" asp-format="{0:yyyy-MM-ddTHH:mm}"/>
                <span asp-validation-for="Transaction.Timestamp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Transaction.Category" class="control-label"></label>
                <input asp-for="Transaction.Category" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Transaction.Notes" class="control-label"></label>
                <input asp-for="Transaction.Notes" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./TransactionIndex">Back to List</a>
</div>

<div>
    <a asp-page-handler="Delete" asp-route-id="@Model.Transaction.Id">Delete</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Transactions/TransactionIndex.cshtml
@page
@model ChoreMgr.Pages.Transactions.TransactionIndexModel

@{
    ViewData["Title"] = "Transactions";
}

<h1>Transactions</h1>
<p>Summary: @Model.Total</p>
<div style="float: left">
    <a asp-page="TransactionCreate">Create New</a>
</div>
<div style="float: right">
    @if (Model.IsDebug)
    {
        <a asp-page-handler="ProdSync">Prod Sync</a>  <br />
    }
    <a asp-page-handler="Dedup">Dedup</a>  <br />
    <a asp-page-handler="Backup">Backup</a>  <br />
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TransactionList[0].Timestamp)
            </th>
            <th style="text-align:center;">
                @Html.DisplayNameFor(model => model.TransactionList[0].Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TransactionList[0].Name)
            </th>
            <th style="text-align:center;">
                @Html.DisplayNameFor(model => model.TransactionList[0].Amount)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.TransactionList) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Timestamp)
            </td>
            <td style="text-align:center;">
                @Html.DisplayFor(modelItem => item.Category)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td style=@item.AmountStyle>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                <a asp-page-handler="Dup" asp-route-id="@item.Id">Dup</a>
                <a asp-page="./TransactionEdit" asp-route-id="@item.Id">Edit</a>
            </td>
        </tr>
}
    </tbody>
</table>
@Model.ContextName
    